services:
  postgres:
    image: postgres
    container_name: auth-postgres
    environment:
      POSTGRES_USER: myname
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
